#! /bin/bash
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y curl gnupg2 lsb-release git meld build-essential libfontconfig1 mesa-common-dev libglu1-mesa-dev

cd $HOME

# Set Default AIMS System Settings
#background="/background.jpg"
#gsettings set org.gnome.desktop.background picture-uri file://$PWD$background
#
#newicon="/user_avatar.png"
#icon=`echo $(ls /var/lib/AccountsService/icons)`
#iconpath=$(realpath /var/lib/AccountsService/icons/$icon)
#sudo cp $PWD$newicon $iconpath

# ##############################################################################
# Uninstall Unneeded Default Programs
sudo apt-get -y purge gnome-games gnome-games-common

sudo apt-get -y purge aisleriot gnome-mahjongg gnome-mines gnome-sudoku
sudo apt-get -y purge simple-scan gnome-todo
sudo apt -y autoremove

#sudo apt purge rhythmbox rhythmbox-data rhythmbox-plugin-alternative-toolbar rhythmbox-plugins
#sudo apt purge remmina remmina-common remmina-plugin-rdp remmina-plugin-secret remmina-plugin-vnc


# ##############################################################################
# Useful tools
sudo apt-get install tree


# ##############################################################################
# ROS1 packages source   ...if using a proxy server may need to use curl. see ROS webpage install instructions
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# ROS2 packages source
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'

sudo apt update -y

# ##############################################################################
# ROS1 install
sudo apt install -y ros-melodic-desktop
sudo apt install -y python-wstool python-catkin-tools
sudo apt install -y ros-melodic-perception ros-melodic-urdf-tutorials ros-melodic-moveit
sudo apt install -y ros-melodic-warehouse-ros ros-melodic-warehouse-ros-mongo
sudo apt install -y ros-melodic-openni-camera ros-melodic-openni-launch ros-melodic-openni2-camera ros-melodic-openni2-launch
sudo apt install -y pcl-tools
sudo apt-get install -y ros-melodic-trac-ik-kinematics-plugin

# ROS2 install
sudo apt install -y ros-dashing-desktop
sudo apt install -y python3-colcon-common-extensions python3-argcomplete

# ##############################################################################
# Install ROS Industrial
sudo apt-get install ros-melodic-industrial-core
sudo apt-get install ros-melodic-joint-state-publisher-gui

# ##############################################################################
# Install Gazebo 9 for ROS w/ packages
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
cat /etc/apt/sources.list.d/gazebo-stable.list
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -

sudo apt-get update

sudo apt-get install -y gazebo9
sudo apt-get install -y ros-melodic-gazebo-ros
sudo apt-get install -y ros-melodic-gazebo-ros-pkgs ros-melodic-gazebo-ros-control

# PID Controllers for Robot Simulation
sudo apt-get install -y ros-melodic-position-controllers
sudo apt-get install -y ros-melodic-joint-state-controller
# sudo apt-get install ros-indigo-effort-controllers


# ##############################################################################
# Install Qt Creator with ROS plugin
# NOTE: no way (yet?) to do headless QT IFW install.  Do this last, but will require user action
QTFILE=qtcreator-ros-bionic-latest-online-installer.run
wget -q https://qtcreator-ros.datasys.swri.edu/downloads/installers/bionic/$QTFILE
chmod u+x $QTFILE
./$QTFILE
rm $QTFILE


# ##############################################################################
# Update ~/.bashrc file to source the ROS melodic environment
echo "# ROS ALIAS: " >> ~/.bashrc
echo "alias ros1='source /./opt/ros/melodic/setup.bash' " >> ~/.bashrc
echo "alias ros2='source /./opt/ros/eloquent/setup.bash' " >> ~/.bashrc
echo "export ROSCONSOLE_FORMAT='[${severity}] [${time}] [${node}] [${logger}]: ${message}' " >> ~/.bashrc
source ~/.bashrc

# Intialize to ROS1
source /./opt/ros/melodic/setup.bash

# ##############################################################################
# First Run of ROS Setup Things
# Install rosdep
sudo apt-get install -y python-rosdep
sudo rosdep init
rosdep update

sudo apt-get update
sudo apt update
