#! /bin/bash

cd $HOME
sudo apt-get update
sudo apt update
sudo apt upgrade -y


# Setup locale as UTF-8
locale 
sudo apt install -y locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8


# ##############################################################################
# Install System Tools & Libraries 
sudo apt install -y \
  curl \
  gnupg2 \
  lsb-release \
  git \
  meld \
  build-essential \
  libfontconfig1 \
  mesa-common-dev \
  libglu1-mesa-dev \
  tree


# ##############################################################################
# Setup  ROS2  source
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Update Sources
sudo apt-get update
sudo apt update


# ##############################################################################
# ROS2 packages install
sudo apt install -y ros-humble-desktop
sudo apt install -y ros-humble-xacro

sudo apt install -y ros-humble-moveit

sudo apt install -y ros-humble-image-publisher


# ##############################################################################
# Install ROS Industrial Specific Packages
# w/ PID Controllers for Robot Simulation

# sudo apt install -y \
#   ros-humble-ros-industrial-cmake-boilerplate
  
sudo apt install -y \
  ros-humble-ros2-control \
  ros-humble-ros2-controllers \
  ros-humble-joint-state-publisher \
  ros-humble-joint-state-publisher-gui \
  ros-humble-position-controllers
  # ros-humble-joint-state-controller
  
  
# ##############################################################################
# Install Gazebo/Ignition for Simulation

# Source
sudo wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

sudo apt update

# Install
sudo apt install -y ignition-fortress
sudo apt install -y ros-humble-ros-ign


# ##############################################################################
# Dependencies needed for building/managing ROS packages
sudo apt install -y \
  python3-rosdep \
  python3-colcon-common-extensions \
  python3-argcomplete \
  python3-osrf-pycommon \
  python3-wstool \
  python3-vcstool \
  build-essential


# ##############################################################################
# Update ~/.bashrc file to source the ROS melodic environment
echo "# ROS ALIAS: " >> ~/.bashrc
echo "alias ros2-humble='source /./opt/ros/humble/setup.bash' " >> ~/.bashrc
source ~/.bashrc


# ##############################################################################
# Setup ROSdep
sudo rosdep init
rosdep update


# ##############################################################################
# Final Cleanup
sudo apt-get update
sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y

