#! /bin/bash

cd $HOME
sudo apt-get update
sudo apt update
sudo apt upgrade -y


# Setup locale as UTF-8
locale 
sudo apt install -y locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8


# ##############################################################################
# Install System Tools & Libraries 
sudo apt install -y \
  curl \
  gnupg2 \
  lsb-release \
  git \
  meld \
  build-essential \
  libfontconfig1 \
  mesa-common-dev \
  libglu1-mesa-dev \
  tree


# ##############################################################################
# Setup ROS1 & ROS2  source

# ROS 1
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

# ROS 2
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Update Sources
sudo apt-get update
sudo apt update


# ##############################################################################
# ROS1 install
sudo apt install -y ros-noetic-desktop
sudo apt install -y ros-noetic-catkin

sudo apt install -y \
  ros-noetic-perception \
  ros-noetic-moveit \
  ros-noetic-moveit-visual-tools

sudo apt install -y \
  ros-noetic-warehouse-ros\
  ros-noetic-warehouse-ros-mongo

sudo apt install -y \
  ros-noetic-image-publisher \
  ros-noetic-realsense2-camera \
  ros-noetic-realsense2-description

sudo apt install -y ros-noetic-trac-ik-kinematics-plugin
sudo apt install -y pcl-tools


# ##############################################################################
# ROS2 install
sudo apt install -y ros-foxy-desktop
sudo apt install -y python3-colcon-common-extensions python3-argcomplete
sudo apt install -y ros-foxy-ros1-bridge ros-foxy-xacro

sudo apt install -y ros-foxy-moveit

sudo apt install -y \
  ros-foxy-image-publisher \
  ros-foxy-realsense2-camera \
  ros-foxy-realsense2-description


# ##############################################################################
# Install ROS Industrial Specific Packages
# w/ PID Controllers for Robot Simulation
# Note: the "industrial_core" package has no plans for direct port to ROS 2.

sudo apt install -y \
  ros-noetic-industrial-core \
  ros-noetic-ros-industrial-cmake-boilerplate

sudo apt install -y \
  ros-noetic-ros-controllers \
  ros-noetic-position-controllers \
  ros-noetic-joint-state-controller \
  ros-noetic-joint-state-publisher \
  ros-noetic-joint-state-publisher-gui \
  ros-noetic-moveit-simple-controller-manager

sudo apt install -y \
  ros-foxy-ros-industrial-cmake-boilerplate
  
sudo apt install -y \
  ros-foxy-ros2-control \
  ros-foxy-ros2-controllers \
  ros-foxy-joint-state-publisher \
  ros-foxy-joint-state-publisher-gui \
  ros-foxy-joint-state-controller \
  ros-foxy-position-controllers \
  
  
# ##############################################################################
# Install Gazebo for ROS w/ packages

# Ignition Source
sudo wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

sudo apt update

# Install Ignition
sudo apt install -y ignition-fortress
sudo apt install -y ros-noetic-ros-ign
sudo apt install -y ros-foxy-ros-ign

# Install Gazebo
sudo apt install -y \
  ros-noetic-gazebo-ros \
  ros-noetic-gazebo-ros-control


# ##############################################################################
# Dependencies needed for building/managing ROS packages
sudo apt install -y \
  python3-rosdep \
  python3-catkin-tools \
  python3-osrf-pycommon \
  python3-wstool \
  python3-vcstool \
  build-essential


# ##############################################################################
# Update ~/.bashrc file to include shortcuts to source the ROS environment
echo "# ROS ALIAS: " >> ~/.bashrc
echo "alias ros1-noetic='source /./opt/ros/noetic/setup.bash' " >> ~/.bashrc
echo "alias ros2-foxy='source /./opt/ros/foxy/setup.bash' " >> ~/.bashrc
#echo "export ROSCONSOLE_FORMAT='[${severity}] [${time}] [${node}] [${logger}]: ${message}' " >> ~/.bashrc
source ~/.bashrc


# ##############################################################################
# Setup ROSdep
sudo rosdep init
rosdep update


# ##############################################################################
# Final Cleanup
sudo apt-get update
sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y

