#! /bin/bash

cd $HOME
sudo apt-get update
sudo apt update
sudo apt upgrade -y


# Setup locale as UTF-8
locale 
sudo apt install -y locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8


# ##############################################################################
# Install System Tools & Libraries 
sudo apt install -y \
  curl \
  gnupg2 \
  lsb-release \
  git \
  meld \
  build-essential \
  libfontconfig1 \
  mesa-common-dev \
  libglu1-mesa-dev \
  tree


# ##############################################################################
# ROS1 packages source   ...if using a proxy server may need to use curl. see ROS webpage install instructions
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

sudo apt-get update
sudo apt update


# ##############################################################################
# ROS1 install
sudo apt install -y ros-melodic-desktop
sudo apt install -y python-wstool python-catkin-tools
sudo apt install -y ros-melodic-moveit
sudo apt install -y ros-melodic-moveit-visual-tools
sudo apt install -y ros-melodic-perception
sudo apt install -y ros-melodic-warehouse-ros ros-melodic-warehouse-ros-mongo
sudo apt install -y pcl-tools
sudo apt install -y ros-melodic-trac-ik-kinematics-plugin
sudo apt install -y ros-melodic-industrial-core

sudo apt install -y ros-melodic-image-publisher


# ##############################################################################
# Install ROS Industrial
sudo apt install -y ros-melodic-industrial-core
sudo apt install -y ros-melodic-joint-state-publisher-gui

  
# ##############################################################################
# Install Gazebo 9 for ROS w/ packages
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
cat /etc/apt/sources.list.d/gazebo-stable.list
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -

sudo apt update

sudo apt install -y gazebo9
sudo apt install -y ros-melodic-gazebo-ros
sudo apt install -y ros-melodic-gazebo-ros-pkgs ros-melodic-gazebo-ros-control

# PID Controllers for Robot Simulation
sudo apt install -y ros-melodic-position-controllers
sudo apt install -y ros-melodic-joint-state-controller
sudo apt install -y ros-melodic-effort-controllers


# ##############################################################################
# Install Qt Creator with ROS plugin
# NOTE: no way (yet?) to do headless QT IFW install.  Do this last, but will require user action
QTFILE=qtcreator-ros-bionic-latest-online-installer.run
wget -q https://qtcreator-ros.datasys.swri.edu/downloads/installers/bionic/$QTFILE
chmod u+x $QTFILE
./$QTFILE
rm $QTFILE


# ##############################################################################
# Update ~/.bashrc file to source the ROS melodic environment
echo "# ROS ALIAS: " >> ~/.bashrc
echo "alias setup-ros1='source /./opt/ros/melodic/setup.bash' " >> ~/.bashrc
source ~/.bashrc

# Intialize to ROS1
source /./opt/ros/melodic/setup.bash


# ##############################################################################
# Dependencies needed for building/managing ROS packages
sudo apt install -y \
  python-rosdep \
  python-rosinstall \
  python-rosinstall-generator \
  python-wstool \
  python-vcstool


# ##############################################################################
# Setup ROS Dependency Tool
sudo rosdep init
rosdep update


# ##############################################################################
# Final Cleanup
sudo apt-get update
sudo apt update
sudo apt upgrade -y
sudo apt -y autoremove
